body:
  - type: textBlock
    attributes:
      name: description
      description: >
        Search Notion pages and databases
  - type: input
    attributes:
      name: notion_token
      label: 'Notion Integration Token'
      description: Enter an integration token created from the Notion website.